create table if not exists private.facebook_oauth_states (
  state_hash text primary key,
  user_id uuid not null,
  workspace_id uuid not null,
  brand_id uuid not null,
  return_url text not null,
  redirect_uri text not null,
  expires_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint facebook_oauth_states_hash_check
    check (state_hash ~ '^[0-9a-f]{64}$')
);

create index if not exists facebook_oauth_states_expires_at_idx
  on private.facebook_oauth_states (expires_at);

create table if not exists private.facebook_oauth_attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  workspace_id uuid not null,
  brand_id uuid not null,
  outcome text not null,
  step text not null,
  provider_code text,
  page_count integer,
  created_at timestamptz not null default now(),
  constraint facebook_oauth_attempts_outcome_check
    check (outcome in ('success', 'cancelled', 'error')),
  constraint facebook_oauth_attempts_page_count_check
    check (page_count is null or page_count >= 0)
);

create index if not exists facebook_oauth_attempts_created_at_idx
  on private.facebook_oauth_attempts (created_at desc);

revoke all on private.facebook_oauth_states from public, anon, authenticated;
revoke all on private.facebook_oauth_attempts from public, anon, authenticated;

create or replace function public.create_facebook_oauth_state(
  state_hash_value text,
  actor_user_id_value uuid,
  target_workspace_id uuid,
  target_brand_id uuid,
  return_url_value text,
  redirect_uri_value text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_hash text := lower(trim(state_hash_value));
  normalized_return_url text := trim(return_url_value);
  normalized_redirect_uri text := trim(redirect_uri_value);
begin
  if normalized_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Estado OAuth inválido.';
  end if;

  if not (
    normalized_return_url in (
      'https://studiov.pt/html/dashboard/settings.html',
      'https://www.studiov.pt/html/dashboard/settings.html'
    )
    or normalized_return_url ~ '^http://(localhost|127[.]0[.]0[.]1)(:[0-9]{1,5})?/html/dashboard/settings[.]html$'
  ) then
    raise exception 'URL de retorno OAuth inválida.';
  end if;

  if normalized_redirect_uri <> 'https://frwnelhsmcyingkblego.supabase.co/functions/v1/facebook-oauth-callback' then
    raise exception 'Redirect URI do Facebook inválido.';
  end if;

  if not exists (
    select 1
    from public.workspace_members wm
    where wm.workspace_id = target_workspace_id
      and wm.user_id = actor_user_id_value
      and wm.status = 'active'
      and wm.role in ('owner', 'admin')
  ) then
    raise exception 'O utilizador não possui permissão para conectar contas.';
  end if;

  if not exists (
    select 1
    from public.brands b
    where b.id = target_brand_id
      and b.workspace_id = target_workspace_id
      and b.status = 'active'
  ) then
    raise exception 'Marca ativa não encontrada neste workspace.';
  end if;

  delete from private.facebook_oauth_states
  where expires_at <= now();

  insert into private.facebook_oauth_states (
    state_hash,
    user_id,
    workspace_id,
    brand_id,
    return_url,
    redirect_uri,
    expires_at
  ) values (
    normalized_hash,
    actor_user_id_value,
    target_workspace_id,
    target_brand_id,
    normalized_return_url,
    normalized_redirect_uri,
    now() + interval '10 minutes'
  )
  on conflict (state_hash) do nothing;
end;
$$;

create or replace function public.consume_facebook_oauth_state(
  state_hash_value text
)
returns table (
  actor_user_id uuid,
  workspace_id uuid,
  brand_id uuid,
  return_url text,
  redirect_uri text
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  normalized_hash text := lower(trim(state_hash_value));
begin
  if normalized_hash !~ '^[0-9a-f]{64}$' then
    return;
  end if;

  delete from private.facebook_oauth_states
  where expires_at <= now();

  return query
  delete from private.facebook_oauth_states oauth_state
  where oauth_state.state_hash = normalized_hash
    and oauth_state.expires_at > now()
  returning
    oauth_state.user_id,
    oauth_state.workspace_id,
    oauth_state.brand_id,
    oauth_state.return_url,
    oauth_state.redirect_uri;
end;
$$;

create or replace function public.record_facebook_oauth_attempt(
  actor_user_id_value uuid,
  target_workspace_id uuid,
  target_brand_id uuid,
  outcome_value text,
  step_value text,
  provider_code_value text default null,
  page_count_value integer default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if outcome_value not in ('success', 'cancelled', 'error') then
    raise exception 'Resultado OAuth inválido.';
  end if;

  insert into private.facebook_oauth_attempts (
    user_id,
    workspace_id,
    brand_id,
    outcome,
    step,
    provider_code,
    page_count
  ) values (
    actor_user_id_value,
    target_workspace_id,
    target_brand_id,
    outcome_value,
    left(coalesce(nullif(trim(step_value), ''), 'unknown'), 80),
    left(nullif(trim(provider_code_value), ''), 220),
    page_count_value
  );
end;
$$;

create or replace function public.connect_facebook_page(
  target_workspace_id uuid,
  target_brand_id uuid,
  actor_user_id uuid,
  external_account_id_value text,
  account_name_value text,
  access_token_value text,
  profile_url_value text default null,
  avatar_url_value text default null,
  scopes_value text[] default array[]::text[],
  public_metadata_value jsonb default '{}'::jsonb
)
returns public.social_accounts
language plpgsql
security definer
set search_path = ''
as $$
declare
  account_record public.social_accounts;
begin
  select *
  into account_record
  from public.connect_social_account(
    target_workspace_id,
    target_brand_id,
    actor_user_id,
    'facebook',
    external_account_id_value,
    account_name_value,
    access_token_value,
    null,
    null,
    'page',
    profile_url_value,
    avatar_url_value,
    'Bearer',
    scopes_value,
    null,
    public_metadata_value
  );

  update public.social_accounts
  set
    status = 'connected',
    connected_at = coalesce(connected_at, now()),
    last_error_code = null,
    last_error_at = null
  where id = account_record.id
  returning * into account_record;

  return account_record;
end;
$$;

revoke all on function public.create_facebook_oauth_state(text, uuid, uuid, uuid, text, text) from public, anon, authenticated;
revoke all on function public.consume_facebook_oauth_state(text) from public, anon, authenticated;
revoke all on function public.record_facebook_oauth_attempt(uuid, uuid, uuid, text, text, text, integer) from public, anon, authenticated;
revoke all on function public.connect_facebook_page(uuid, uuid, uuid, text, text, text, text, text, text[], jsonb) from public, anon, authenticated;

grant execute on function public.create_facebook_oauth_state(text, uuid, uuid, uuid, text, text) to service_role;
grant execute on function public.consume_facebook_oauth_state(text) to service_role;
grant execute on function public.record_facebook_oauth_attempt(uuid, uuid, uuid, text, text, text, integer) to service_role;
grant execute on function public.connect_facebook_page(uuid, uuid, uuid, text, text, text, text, text, text[], jsonb) to service_role;
