-- Planos comerciais, créditos extra e consumo seguro de gerações de texto.

insert into public.billing_plans (
    code,
    name,
    description,
    currency,
    monthly_price_cents,
    yearly_price_cents,
    limits,
    features,
    is_public,
    is_active,
    sort_order
)
values
    (
        'free',
        'Básico',
        'Para começar a organizar e criar conteúdo.',
        'EUR',
        0,
        0,
        jsonb_build_object(
            'brands', 1,
            'members', 1,
            'storage_bytes', 524288000,
            'social_accounts', 2,
            'ai_text_generations_monthly', 20,
            'ai_image_generations_monthly', 0
        ),
        jsonb_build_object(
            'ai_text_generation', true,
            'ai_image_generation', false,
            'calendar', true,
            'analytics', true,
            'content_planner', true
        ),
        true,
        true,
        0
    ),
    (
        'pro',
        'Pro',
        'Para profissionais que gerem conteúdo com frequência.',
        'EUR',
        1900,
        18000,
        jsonb_build_object(
            'brands', 10,
            'members', 1,
            'storage_bytes', 10737418240,
            'social_accounts', 15,
            'ai_text_generations_monthly', 300,
            'ai_image_generations_monthly', 0
        ),
        jsonb_build_object(
            'ai_text_generation', true,
            'ai_image_generation', false,
            'calendar', true,
            'analytics', true,
            'content_planner', true,
            'priority_support', true
        ),
        true,
        true,
        1
    ),
    (
        'business',
        'Empresa',
        'Para equipas e operações com maior volume de conteúdo.',
        'EUR',
        0,
        0,
        jsonb_build_object(
            'brands', 30,
            'members', 15,
            'storage_bytes', 53687091200,
            'social_accounts', 50,
            'ai_text_generations_monthly', 1000,
            'ai_image_generations_monthly', 0
        ),
        jsonb_build_object(
            'ai_text_generation', true,
            'ai_image_generation', false,
            'calendar', true,
            'analytics', true,
            'content_planner', true,
            'priority_support', true,
            'team_management', true
        ),
        true,
        true,
        2
    )
on conflict (code) do update
set
    name = excluded.name,
    description = excluded.description,
    currency = excluded.currency,
    monthly_price_cents = excluded.monthly_price_cents,
    yearly_price_cents = excluded.yearly_price_cents,
    limits = excluded.limits,
    features = excluded.features,
    is_public = excluded.is_public,
    is_active = excluded.is_active,
    sort_order = excluded.sort_order;


create table public.ai_credit_packs (
    id bigint generated by default as identity primary key,
    code text not null unique,
    name text not null,
    credits bigint not null,
    price_cents bigint not null,
    currency text not null default 'EUR',
    stripe_price_id text,
    is_public boolean not null default true,
    is_active boolean not null default true,
    sort_order integer not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint ai_credit_packs_code_check
        check (code ~ '^[a-z][a-z0-9_]*$'),
    constraint ai_credit_packs_name_check
        check (char_length(trim(name)) between 2 and 100),
    constraint ai_credit_packs_credits_check
        check (credits > 0),
    constraint ai_credit_packs_price_check
        check (price_cents > 0),
    constraint ai_credit_packs_currency_check
        check (currency ~ '^[A-Z]{3}$'),
    constraint ai_credit_packs_sort_order_check
        check (sort_order >= 0)
);

insert into public.ai_credit_packs (
    code,
    name,
    credits,
    price_cents,
    sort_order
)
values
    ('extra_10', '+10 gerações', 10, 149, 0),
    ('extra_50', '+50 gerações', 50, 599, 1),
    ('extra_100', '+100 gerações', 100, 999, 2),
    ('extra_500', '+500 gerações', 500, 3999, 3)
on conflict (code) do update
set
    name = excluded.name,
    credits = excluded.credits,
    price_cents = excluded.price_cents,
    currency = excluded.currency,
    is_public = true,
    is_active = true,
    sort_order = excluded.sort_order;

create trigger set_ai_credit_packs_updated_at
before update on public.ai_credit_packs
for each row execute function public.set_billing_updated_at();


create table public.workspace_ai_credit_balances (
    workspace_id uuid primary key
        references public.workspaces(id) on delete cascade,
    balance bigint not null default 0,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint workspace_ai_credit_balances_balance_check
        check (balance >= 0)
);

create trigger set_workspace_ai_credit_balances_updated_at
before update on public.workspace_ai_credit_balances
for each row execute function public.set_billing_updated_at();


create table public.workspace_ai_credit_ledger (
    id bigint generated by default as identity primary key,
    workspace_id uuid not null
        references public.workspaces(id) on delete cascade,
    reservation_id uuid,
    amount bigint not null,
    reason text not null,
    pack_code text,
    provider text,
    external_payment_id text,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    constraint workspace_ai_credit_ledger_amount_check
        check (amount <> 0),
    constraint workspace_ai_credit_ledger_reason_check
        check (
            reason in (
                'purchase',
                'generation',
                'generation_refund',
                'chargeback',
                'adjustment'
            )
        ),
    constraint workspace_ai_credit_ledger_metadata_check
        check (jsonb_typeof(metadata) = 'object')
);

create index workspace_ai_credit_ledger_workspace_created_idx
    on public.workspace_ai_credit_ledger (workspace_id, created_at desc);

create unique index workspace_ai_credit_ledger_external_payment_idx
    on public.workspace_ai_credit_ledger (provider, external_payment_id)
    where external_payment_id is not null;


create table public.ai_generation_reservations (
    id uuid primary key default gen_random_uuid(),
    workspace_id uuid not null
        references public.workspaces(id) on delete cascade,
    user_id uuid not null
        references auth.users(id) on delete cascade,
    source text not null,
    status text not null default 'reserved',
    usage_month date not null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    finalized_at timestamptz,
    constraint ai_generation_reservations_source_check
        check (source in ('plan', 'credits')),
    constraint ai_generation_reservations_status_check
        check (status in ('reserved', 'committed', 'released')),
    constraint ai_generation_reservations_month_check
        check (extract(day from usage_month) = 1),
    constraint ai_generation_reservations_metadata_check
        check (jsonb_typeof(metadata) = 'object')
);

alter table public.workspace_ai_credit_ledger
    add constraint workspace_ai_credit_ledger_reservation_fkey
    foreign key (reservation_id)
    references public.ai_generation_reservations(id)
    on delete set null;

create index ai_generation_reservations_workspace_created_idx
    on public.ai_generation_reservations (workspace_id, created_at desc);

create index ai_generation_reservations_user_created_idx
    on public.ai_generation_reservations (user_id, created_at desc);


alter table public.ai_credit_packs enable row level security;
alter table public.workspace_ai_credit_balances enable row level security;
alter table public.workspace_ai_credit_ledger enable row level security;
alter table public.ai_generation_reservations enable row level security;

create policy "Authenticated users can view active AI credit packs"
on public.ai_credit_packs
for select
to authenticated
using (is_active = true and is_public = true);

revoke all on table public.ai_credit_packs from anon, authenticated;
grant select on table public.ai_credit_packs to authenticated;
grant all on table public.ai_credit_packs to service_role;

revoke all on table public.workspace_ai_credit_balances from anon, authenticated;
revoke all on table public.workspace_ai_credit_ledger from anon, authenticated;
revoke all on table public.ai_generation_reservations from anon, authenticated;
grant all on table public.workspace_ai_credit_balances to service_role;
grant all on table public.workspace_ai_credit_ledger to service_role;
grant all on table public.ai_generation_reservations to service_role;

revoke all on sequence public.ai_credit_packs_id_seq from anon, authenticated;
revoke all on sequence public.workspace_ai_credit_ledger_id_seq from anon, authenticated;
grant all on sequence public.ai_credit_packs_id_seq to service_role;
grant all on sequence public.workspace_ai_credit_ledger_id_seq to service_role;


create or replace function public.get_ai_text_generation_quota(
    workspace_id_value uuid
)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    current_user_id uuid;
    usage_month_value date;
    plan_code_value text;
    plan_name_value text;
    monthly_limit_value bigint;
    plan_used_value bigint;
    credit_balance_value bigint;
begin
    current_user_id := (select auth.uid());

    if current_user_id is null then
        raise exception 'Utilizador não autenticado.';
    end if;

    if not exists (
        select 1
        from public.workspaces w
        where w.id = workspace_id_value
          and w.status = 'active'
          and (
              w.owner_id = current_user_id
              or exists (
                  select 1
                  from public.workspace_members wm
                  where wm.workspace_id = w.id
                    and wm.user_id = current_user_id
                    and wm.status = 'active'
              )
          )
    ) then
        raise exception 'Workspace não encontrado ou sem acesso.';
    end if;

    usage_month_value := date_trunc('month', current_date)::date;

    select
        bp.code,
        bp.name,
        greatest(
            coalesce((bp.limits ->> 'ai_text_generations_monthly')::bigint, 0),
            0
        )
    into
        plan_code_value,
        plan_name_value,
        monthly_limit_value
    from public.workspace_subscriptions ws
    join public.billing_plans bp on bp.id = ws.plan_id
    where ws.workspace_id = workspace_id_value
      and ws.is_current = true
      and bp.is_active = true
    order by ws.created_at desc
    limit 1;

    if plan_code_value is null then
        raise exception 'Plano ativo não encontrado para este workspace.';
    end if;

    select coalesce(wu.ai_text_generations, 0)
    into plan_used_value
    from public.workspace_usage_monthly wu
    where wu.workspace_id = workspace_id_value
      and wu.usage_month = usage_month_value;

    select coalesce(wacb.balance, 0)
    into credit_balance_value
    from public.workspace_ai_credit_balances wacb
    where wacb.workspace_id = workspace_id_value;

    plan_used_value := coalesce(plan_used_value, 0);
    credit_balance_value := coalesce(credit_balance_value, 0);

    return jsonb_build_object(
        'workspaceId', workspace_id_value,
        'planCode', plan_code_value,
        'planName', plan_name_value,
        'usageMonth', usage_month_value,
        'resetsAt', (usage_month_value + interval '1 month')::date,
        'planUsed', plan_used_value,
        'monthlyLimit', monthly_limit_value,
        'planRemaining', greatest(monthly_limit_value - plan_used_value, 0),
        'purchasedCredits', credit_balance_value,
        'totalAvailable', greatest(monthly_limit_value - plan_used_value, 0)
            + credit_balance_value
    );
end;
$$;


create or replace function public.reserve_ai_text_generation(
    workspace_id_value uuid,
    actor_user_id_value uuid
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    usage_month_value date;
    plan_code_value text;
    plan_name_value text;
    monthly_limit_value bigint;
    plan_used_value bigint;
    credit_balance_value bigint;
    reservation_id_value uuid;
    reservation_source_value text;
begin
    if workspace_id_value is null or actor_user_id_value is null then
        raise exception 'Workspace e utilizador são obrigatórios.';
    end if;

    if not exists (
        select 1
        from public.workspaces w
        where w.id = workspace_id_value
          and w.status = 'active'
          and (
              w.owner_id = actor_user_id_value
              or exists (
                  select 1
                  from public.workspace_members wm
                  where wm.workspace_id = w.id
                    and wm.user_id = actor_user_id_value
                    and wm.status = 'active'
              )
          )
    ) then
        raise exception 'Workspace não encontrado ou sem acesso.';
    end if;

    usage_month_value := date_trunc('month', current_date)::date;

    select
        bp.code,
        bp.name,
        greatest(
            coalesce((bp.limits ->> 'ai_text_generations_monthly')::bigint, 0),
            0
        )
    into
        plan_code_value,
        plan_name_value,
        monthly_limit_value
    from public.workspace_subscriptions ws
    join public.billing_plans bp on bp.id = ws.plan_id
    where ws.workspace_id = workspace_id_value
      and ws.is_current = true
      and bp.is_active = true
    order by ws.created_at desc
    limit 1;

    if plan_code_value is null then
        raise exception 'Plano ativo não encontrado para este workspace.';
    end if;

    insert into public.workspace_usage_monthly (
        workspace_id,
        usage_month,
        ai_text_generations
    )
    values (
        workspace_id_value,
        usage_month_value,
        0
    )
    on conflict (workspace_id, usage_month) do nothing;

    update public.workspace_usage_monthly
    set ai_text_generations = ai_text_generations + 1
    where workspace_id = workspace_id_value
      and usage_month = usage_month_value
      and ai_text_generations < monthly_limit_value
    returning ai_text_generations
    into plan_used_value;

    if plan_used_value is not null then
        reservation_source_value := 'plan';
    else
        update public.workspace_ai_credit_balances
        set balance = balance - 1
        where workspace_id = workspace_id_value
          and balance > 0
        returning balance
        into credit_balance_value;

        if credit_balance_value is not null then
            reservation_source_value := 'credits';
        end if;
    end if;

    select coalesce(wu.ai_text_generations, 0)
    into plan_used_value
    from public.workspace_usage_monthly wu
    where wu.workspace_id = workspace_id_value
      and wu.usage_month = usage_month_value;

    select coalesce(wacb.balance, 0)
    into credit_balance_value
    from public.workspace_ai_credit_balances wacb
    where wacb.workspace_id = workspace_id_value;

    plan_used_value := coalesce(plan_used_value, 0);
    credit_balance_value := coalesce(credit_balance_value, 0);

    if reservation_source_value is null then
        return jsonb_build_object(
            'allowed', false,
            'message', 'O limite mensal foi atingido e não existem créditos extra disponíveis.',
            'quota', jsonb_build_object(
                'planCode', plan_code_value,
                'planName', plan_name_value,
                'usageMonth', usage_month_value,
                'resetsAt', (usage_month_value + interval '1 month')::date,
                'planUsed', plan_used_value,
                'monthlyLimit', monthly_limit_value,
                'planRemaining', greatest(monthly_limit_value - plan_used_value, 0),
                'purchasedCredits', credit_balance_value,
                'totalAvailable', greatest(monthly_limit_value - plan_used_value, 0)
                    + credit_balance_value
            )
        );
    end if;

    insert into public.ai_generation_reservations (
        workspace_id,
        user_id,
        source,
        usage_month
    )
    values (
        workspace_id_value,
        actor_user_id_value,
        reservation_source_value,
        usage_month_value
    )
    returning id into reservation_id_value;

    if reservation_source_value = 'credits' then
        insert into public.workspace_ai_credit_ledger (
            workspace_id,
            reservation_id,
            amount,
            reason,
            metadata
        )
        values (
            workspace_id_value,
            reservation_id_value,
            -1,
            'generation',
            jsonb_build_object('userId', actor_user_id_value)
        );
    end if;

    return jsonb_build_object(
        'allowed', true,
        'reservationId', reservation_id_value,
        'source', reservation_source_value,
        'quota', jsonb_build_object(
            'planCode', plan_code_value,
            'planName', plan_name_value,
            'usageMonth', usage_month_value,
            'resetsAt', (usage_month_value + interval '1 month')::date,
            'planUsed', plan_used_value,
            'monthlyLimit', monthly_limit_value,
            'planRemaining', greatest(monthly_limit_value - plan_used_value, 0),
            'purchasedCredits', credit_balance_value,
            'totalAvailable', greatest(monthly_limit_value - plan_used_value, 0)
                + credit_balance_value
        )
    );
end;
$$;


create or replace function public.finalize_ai_text_generation(
    reservation_id_value uuid,
    success_value boolean
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    reservation_record public.ai_generation_reservations%rowtype;
begin
    select *
    into reservation_record
    from public.ai_generation_reservations agr
    where agr.id = reservation_id_value
    for update;

    if reservation_record.id is null then
        raise exception 'Reserva de geração não encontrada.';
    end if;

    if reservation_record.status <> 'reserved' then
        return jsonb_build_object(
            'reservationId', reservation_record.id,
            'status', reservation_record.status
        );
    end if;

    if success_value then
        update public.ai_generation_reservations
        set
            status = 'committed',
            finalized_at = now()
        where id = reservation_record.id;

        return jsonb_build_object(
            'reservationId', reservation_record.id,
            'status', 'committed'
        );
    end if;

    if reservation_record.source = 'plan' then
        update public.workspace_usage_monthly
        set ai_text_generations = greatest(ai_text_generations - 1, 0)
        where workspace_id = reservation_record.workspace_id
          and usage_month = reservation_record.usage_month;
    else
        insert into public.workspace_ai_credit_balances (
            workspace_id,
            balance
        )
        values (
            reservation_record.workspace_id,
            1
        )
        on conflict (workspace_id) do update
        set balance = public.workspace_ai_credit_balances.balance + 1;

        insert into public.workspace_ai_credit_ledger (
            workspace_id,
            reservation_id,
            amount,
            reason
        )
        values (
            reservation_record.workspace_id,
            reservation_record.id,
            1,
            'generation_refund'
        );
    end if;

    update public.ai_generation_reservations
    set
        status = 'released',
        finalized_at = now()
    where id = reservation_record.id;

    return jsonb_build_object(
        'reservationId', reservation_record.id,
        'status', 'released'
    );
end;
$$;


create or replace function public.grant_ai_credits(
    workspace_id_value uuid,
    credits_value bigint,
    pack_code_value text,
    provider_value text,
    external_payment_id_value text,
    metadata_value jsonb default '{}'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    ledger_id_value bigint;
    new_balance_value bigint;
begin
    if credits_value <= 0 then
        raise exception 'A quantidade de créditos deve ser positiva.';
    end if;

    if nullif(trim(provider_value), '') is null
       or nullif(trim(external_payment_id_value), '') is null then
        raise exception 'O provedor e o identificador do pagamento são obrigatórios.';
    end if;

    if metadata_value is null or jsonb_typeof(metadata_value) <> 'object' then
        raise exception 'metadata deve ser um objeto JSON.';
    end if;

    insert into public.workspace_ai_credit_ledger (
        workspace_id,
        amount,
        reason,
        pack_code,
        provider,
        external_payment_id,
        metadata
    )
    values (
        workspace_id_value,
        credits_value,
        'purchase',
        pack_code_value,
        lower(trim(provider_value)),
        trim(external_payment_id_value),
        metadata_value
    )
    on conflict (provider, external_payment_id)
        where external_payment_id is not null
    do nothing
    returning id into ledger_id_value;

    if ledger_id_value is null then
        select coalesce(balance, 0)
        into new_balance_value
        from public.workspace_ai_credit_balances
        where workspace_id = workspace_id_value;

        return jsonb_build_object(
            'granted', false,
            'duplicate', true,
            'balance', coalesce(new_balance_value, 0)
        );
    end if;

    insert into public.workspace_ai_credit_balances (
        workspace_id,
        balance
    )
    values (
        workspace_id_value,
        credits_value
    )
    on conflict (workspace_id) do update
    set balance = public.workspace_ai_credit_balances.balance + excluded.balance
    returning balance into new_balance_value;

    return jsonb_build_object(
        'granted', true,
        'duplicate', false,
        'balance', new_balance_value
    );
end;
$$;


revoke all on function public.get_ai_text_generation_quota(uuid)
    from public, anon;
grant execute on function public.get_ai_text_generation_quota(uuid)
    to authenticated, service_role;

revoke all on function public.reserve_ai_text_generation(uuid, uuid)
    from public, anon, authenticated;
grant execute on function public.reserve_ai_text_generation(uuid, uuid)
    to service_role;

revoke all on function public.finalize_ai_text_generation(uuid, boolean)
    from public, anon, authenticated;
grant execute on function public.finalize_ai_text_generation(uuid, boolean)
    to service_role;

revoke all on function public.grant_ai_credits(uuid, bigint, text, text, text, jsonb)
    from public, anon, authenticated;
grant execute on function public.grant_ai_credits(uuid, bigint, text, text, text, jsonb)
    to service_role;
