export const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export function sid(v:any){return typeof v==="string"?v:v?.id||null}
export function iso(v:any){return typeof v==="number"?new Date(v*1000).toISOString():null}
function period(s:any){const i=s.items?.data?.[0]||{};return{start:iso(s.current_period_start??i.current_period_start),end:iso(s.current_period_end??i.current_period_end)}}
function interval(s:any){return s.items?.data?.[0]?.price?.recurring?.interval==="year"?"yearly":"monthly"}
async function stored(db:any,id:string){const{data,error}=await db.from("workspace_subscriptions").select("id,workspace_id,provider_customer_id,metadata").eq("provider","stripe").eq("provider_subscription_id",id).maybeSingle();if(error)throw new Error(error.message);return data}
async function plan(db:any,s:any){const price=s.items?.data?.[0]?.price?.id;if(price){const{data,error}=await db.from("billing_plans").select("id,code").or(`stripe_monthly_price_id.eq.${price},stripe_yearly_price_id.eq.${price}`).eq("is_active",true).maybeSingle();if(error)throw new Error(error.message);if(data)return data}const code=s.metadata?.plan_code;if(!code)return null;const{data,error}=await db.from("billing_plans").select("id,code").eq("code",code).eq("is_active",true).maybeSingle();if(error)throw new Error(error.message);return data}
export async function syncSub(db:any,s:any,eventId:string,extra:any={}){const old=await stored(db,s.id);const workspace=old?.workspace_id||s.metadata?.workspace_id;if(!workspace||!UUID.test(workspace))throw new Error("Workspace da subscrição não encontrado");const pPlan=await plan(db,s);if(!pPlan)throw new Error("Plano da subscrição não encontrado");const p=period(s);const customer=sid(s.customer);const metadata={...(old?.metadata||{}),...(s.metadata||{}),...extra,stripe_event_id:eventId,stripe_subscription_id:s.id,synced_at:new Date().toISOString()};if(!old){const{data,error}=await db.rpc("set_workspace_subscription",{workspace_id_value:workspace,plan_code_value:pPlan.code,status_value:s.status,provider_value:"stripe",billing_interval_value:interval(s),current_period_start_value:p.start||new Date().toISOString(),current_period_end_value:p.end,trial_end_value:iso(s.trial_end),cancel_at_period_end_value:s.cancel_at_period_end===true,provider_customer_id_value:customer,provider_subscription_id_value:s.id,metadata_value:metadata});if(error)throw new Error(error.message);return data}const{data,error}=await db.from("workspace_subscriptions").update({plan_id:pPlan.id,provider_customer_id:customer||old.provider_customer_id,billing_interval:interval(s),status:s.status,current_period_start:p.start,current_period_end:p.end,trial_end:iso(s.trial_end),cancel_at_period_end:s.cancel_at_period_end===true,canceled_at:iso(s.canceled_at),metadata,updated_at:new Date().toISOString()}).eq("id",old.id).select().single();if(error)throw new Error(error.message);return data}
export async function endSub(db:any,s:any,eventId:string){const old=await stored(db,s.id);const workspace=old?.workspace_id||s.metadata?.workspace_id;if(!workspace||!UUID.test(workspace))throw new Error("Workspace da subscrição cancelada não encontrado");const canceled=iso(s.canceled_at)||new Date().toISOString();const customer=sid(s.customer)||old?.provider_customer_id||null;if(old){const{error}=await db.from("workspace_subscriptions").update({status:"canceled",is_current:false,cancel_at_period_end:false,canceled_at:canceled,metadata:{...(old.metadata||{}),...(s.metadata||{}),stripe_event_id:eventId,ended_at:canceled},updated_at:new Date().toISOString()}).eq("id",old.id);if(error)throw new Error(error.message)}const{data,error}=await db.rpc("set_workspace_subscription",{workspace_id_value:workspace,plan_code_value:"free",status_value:"active",provider_value:"stripe",billing_interval_value:"none",current_period_start_value:new Date().toISOString(),current_period_end_value:null,trial_end_value:null,cancel_at_period_end_value:false,provider_customer_id_value:customer,provider_subscription_id_value:null,metadata_value:{stripe_event_id:eventId,previous_stripe_subscription_id:s.id,cancellation_completed_at:canceled}});if(error)throw new Error(error.message);return data}
function invoiceSub(i:any){return sid(i.subscription)||sid(i.parent?.subscription_details?.subscription)}
export async function syncInvoice(db:any,stripe:any,i:any,eventId:string,eventType:string){const subId=invoiceSub(i);const old=subId?await stored(db,subId):null;const workspace=old?.workspace_id||i.metadata?.workspace_id||i.parent?.subscription_details?.metadata?.workspace_id;if(!workspace||!UUID.test(workspace))throw new Error("Workspace da fatura não encontrado");const tax=(i.total_tax_amounts||[]).reduce((n:number,x:any)=>n+(Number(x.amount)||0),0);const{data,error}=await db.rpc("upsert_billing_invoice",{workspace_id_value:workspace,subscription_id_value:old?.id||null,provider_value:"stripe",provider_invoice_id_value:i.id,invoice_number_value:i.number||null,status_value:i.status||"open",currency_value:(i.currency||"eur").toUpperCase(),subtotal_cents_value:Number(i.subtotal)||0,tax_cents_value:tax,total_cents_value:Number(i.total)||0,amount_paid_cents_value:Number(i.amount_paid)||0,amount_due_cents_value:Number(i.amount_remaining) || 0,issued_at_value:iso(i.created),due_at_value:iso(i.due_date),paid_at_value:iso(i.status_transitions?.paid_at),hosted_invoice_url_value:i.hosted_invoice_url||null,invoice_pdf_url_value:i.invoice_pdf||null,metadata_value:{...(i.metadata||{}),stripe_event_id:eventId,stripe_subscription_id:subId,billing_reason:i.billing_reason}});if(error)throw new Error(error.message);if(subId){const s=await stripe.subscriptions.retrieve(subId);await syncSub(db,s,eventId,{source_invoice_id:i.id,source_invoice_event:eventType})}return data}
